"""tasks

Revision ID: 32303c900925
Revises: 49d7fd2dee1c
Create Date: 2018-06-11 17:33:50.191539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32303c900925'
down_revision = '49d7fd2dee1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
